<a href="https://colab.research.google.com/github/CodeFlash101/Kandinsky-2/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape

(tensor([[0.7978, 0.1727, 0.0237, 0.8297, 0.1036, 0.0378, 0.2263],
         [0.4905, 0.4134, 0.2588, 0.0370, 0.6389, 0.2912, 0.6349],
         [0.9770, 0.5060, 0.4068, 0.2419, 0.8921, 0.4281, 0.6979],
         [0.9539, 0.8795, 0.8976, 0.9821, 0.8990, 0.0042, 0.1371],
         [0.5755, 0.5839, 0.1506, 0.1702, 0.0844, 0.7372, 0.2919],
         [0.7849, 0.3137, 0.8378, 0.3056, 0.1902, 0.4530, 0.3941],
         [0.9789, 0.3525, 0.0429, 0.6459, 0.2124, 0.7311, 0.8057]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)
random_tensor_2 = random_tensor_2.T
# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor_2)

tensor([[0.2900],
        [0.8162],
        [1.0803],
        [1.4351],
        [0.9256],
        [0.9218],
        [0.7995]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

X = torch.rand(7, 7)
Y = torch.rand(1, 7)

z = torch.matmul(X, Y.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.cuda.manual_seed(1234)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
A = torch.rand(2, 3).to("cuda")
B = torch.rand(2, 3).to("cuda")
A, B

Device: cuda


(tensor([[0.0237, 0.4910, 0.1235],
         [0.1143, 0.4725, 0.5751]], device='cuda:0'),
 tensor([[0.2952, 0.7967, 0.1957],
         [0.9537, 0.8426, 0.0784]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
X = torch.matmul(A, B.T)
X, X.shape

(tensor([[0.4223, 0.4460],
         [0.5227, 0.5522]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max = X.max()
# Find min
min = X.min()

max, min

(tensor(0.5522, device='cuda:0'), tensor(0.4223, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
arg_max = X.argmax()

# Find arg min
arg_min = X.argmin()

arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed
torch.manual_seed(7)

# Create random tensor
first = torch.rand(1, 1, 1, 10)


# Remove single dimensions
second = first.squeeze()

# Print out tensors and their shapes
first, first.shape, second, second.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [18]:
#heheheheheheheh maza agya mujhe ye exercise krke ab aage ota lge ka. :)